spring:
  application:
    name : example
  datasource:
    url: jdbc:h2:mem:mydb
    #url: jdbc:h2:mem:mydb:file:/data/demo # file-based storage
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
